project:
  type: website

website:
  title: "Chamber of (data) secrets"
  description: "A data science blog by Edun Joshua"
  site-url: https://joshuaolubori.onrender.com
  repo-url: https://github.com/djnavarro/quarto-blog
  # open-graph: true
  search: false
  # twitter-card:
  #   creator: "@djnavarro"
  #   card-style: summary_large_image
  navbar:
    title: false
    background: "#eee"
    left:
      - href: index.qmd
        text: Home
      - href: posts_index.qmd
        text: Posts
    # right:
    #   - text: Sites
    #     menu:
    #     - href: https://djnavarro.net
    #       text: Homepage
    #     - href: https://blog.djnavarro.net
    #       text: Data science blog
    #     - href: https://art.djnavarro.net
    #       text: Generative art
    #     - href: https://papers.djnavarro.net
    #       text: Academic papers
    #     - href: https://djnavarro.net/sites
    #       text: More...
  page-footer:
    left: "Blog made with 💚 and [Quarto](https://quarto.org/), 
    by Edun Joshua. 
    License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."

format:
  html:
    theme: ember.scss
    css: styles.css



